#!/usr/bin/env python3
"""
secure_server.py — Module A: HTTPS Server with TLS (Secure Mitigation)
=======================================================================
SECURITY CONCEPT: Confidentiality via TLS/SSL
This server wraps the same login form in TLS using a self-signed certificate
generated by OpenSSL. Credentials are now encrypted end-to-end, making them
unreadable to any passive network observer (tshark/pyshark will show only
the TLS Handshake, not the plaintext payload).

This directly implements the CIA Triad principle of CONFIDENTIALITY via
Cryptographic Transport-Layer Security (TLS 1.2/1.3).

Pre-requisite: Run generate_certs.sh first to create server.crt and server.key
Test Case: TC-02
"""

import http.server
import ssl
import socketserver
import urllib.parse
import os
import sys

# ----- Configuration -------------------------------------------------------
PORT = 8443            # Standard HTTPS alternate port
HOST = "0.0.0.0"
CERT_FILE = os.path.join(os.path.dirname(__file__), "server.crt")
KEY_FILE  = os.path.join(os.path.dirname(__file__), "server.key")

# The same HTML login form — identical UI, but now encrypted in transit
LOGIN_PAGE_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>InstaLogin - HTTPS Secure Demo</title>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        * {{
            box-sizing: border-box;
            margin: 0;
            padding: 0;
            font-family: 'Outfit', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        }}
        body {{
            background-color: #fafafa;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            padding: 20px;
        }}
        .container {{
            width: 100%;
            max-width: 350px;
            display: flex;
            flex-direction: column;
            gap: 10px;
        }}
        .login-box {{
            background-color: #fff;
            border: 1px solid #dbdbdb;
            border-radius: 8px;
            padding: 40px 30px 25px 30px;
            text-align: center;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
        }}
        .logo {{
            font-size: 36px;
            font-weight: 700;
            margin-bottom: 8px;
            background: linear-gradient(45deg, #f09433 0%, #e6683c 25%, #dc2743 50%, #cc2366 75%, #bc1888 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            font-style: italic;
            letter-spacing: -1px;
        }}
        .demo-badge {{
            display: inline-block;
            padding: 5px 12px;
            font-size: 10px;
            font-weight: 700;
            border-radius: 20px;
            margin-bottom: 24px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            background-color: #e8f5e9;
            color: #2e7d32;
            border: 1px solid #c8e6c9;
        }}
        .form-group {{
            position: relative;
            margin-bottom: 8px;
        }}
        .form-group input {{
            width: 100%;
            padding: 12px 10px;
            background: #fafafa;
            border: 1px solid #dbdbdb;
            border-radius: 4px;
            font-size: 12px;
            color: #262626;
            outline: none;
            transition: border-color 0.2s ease;
        }}
        .form-group input:focus {{
            border-color: #a8a8a8;
            background: #fff;
        }}
        .login-btn {{
            width: 100%;
            background-color: #0095f6;
            color: #fff;
            border: none;
            border-radius: 4px;
            padding: 10px;
            font-size: 14px;
            font-weight: 600;
            cursor: pointer;
            margin-top: 8px;
            transition: background-color 0.2s ease;
        }}
        .login-btn:hover {{
            background-color: #1877f2;
        }}
        .divider {{
            display: flex;
            align-items: center;
            margin: 20px 0;
            color: #8e8e8e;
            font-size: 12px;
            font-weight: 600;
        }}
        .divider::before, .divider::after {{
            content: "";
            flex: 1;
            height: 1px;
            background-color: #dbdbdb;
        }}
        .divider span {{
            padding: 0 10px;
        }}
        .fb-login {{
            color: #385185;
            font-size: 14px;
            font-weight: 600;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 8px;
            cursor: pointer;
            text-decoration: none;
            margin-bottom: 15px;
            margin-top: 10px;
        }}
        .fb-icon {{
            font-weight: bold;
            font-size: 16px;
        }}
        .info-box {{
            background-color: #fff;
            border: 1px solid #dbdbdb;
            border-radius: 8px;
            padding: 20px;
            text-align: center;
            font-size: 14px;
            color: #262626;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
        }}
        .info-box a {{
            color: #0095f6;
            text-decoration: none;
            font-weight: 600;
        }}
        .message-container {{
            margin-top: 15px;
            font-size: 13px;
        }}
    </style>
</head>
<body>
  <div class="container">
    <div class="login-box">
      <div class="logo">InstaLogin</div>
      <span class="demo-badge">🔒 HTTPS SECURE DEMO</span>
      
      <form method="POST" action="/login">
        <div class="form-group">
          <input type="text" name="username" placeholder="Phone number, username, or email" required>
        </div>
        <div class="form-group">
          <input type="password" name="password" placeholder="Password" required>
        </div>
        <button type="submit" class="login-btn">Log In</button>
      </form>
      
      <div class="divider">
        <span>OR</span>
      </div>
      
      <a href="#" class="fb-login">
        <span class="fb-icon">f</span> Log in with Facebook
      </a>
      
      <div class="message-container">
        {message}
      </div>
    </div>
    
    <div class="info-box">
      Don't have an account? <a href="#">Sign up</a>
    </div>
  </div>
</body>
</html>"""


class SecureLoginHandler(http.server.BaseHTTPRequestHandler):
    """
    Identical handler logic to InsecureLoginHandler, but the underlying
    socket is wrapped in an SSLContext — so all bytes on the wire are
    encrypted. tshark will only see TLS record headers, not the POST body.
    """

    def log_message(self, format, *args):
        print(f"  [HTTPS SERVER] {self.address_string()} → {format % args}")

    def do_GET(self):
        if self.path in ("/", "/login"):
            self._serve_login_page("")
        else:
            self.send_error(404, "Not Found")

    def do_POST(self):
        """
        POST body is the same application/x-www-form-urlencoded data,
        but now it travels inside an encrypted TLS record — invisible to sniffers.
        """
        if self.path == "/login":
            content_length = int(self.headers.get("Content-Length", 0))
            post_body = self.rfile.read(content_length).decode("utf-8")

            params = urllib.parse.parse_qs(post_body)
            username = params.get("username", [""])[0]
            password = params.get("password", [""])[0]

            print("\n" + "=" * 60)
            print("  [✔] ENCRYPTED CREDENTIALS DECRYPTED AT SERVER SIDE")
            print(f"       Username : {username}")
            print(f"       Password : {password}")
            print("  [✔] A wire-sniffer sees ONLY the TLS handshake — NOT this!")
            print("=" * 60 + "\n")

            msg = f'<p style="color:green;text-align:center;">Received securely: <b>{username}</b></p>'
            self._serve_login_page(msg)
        else:
            self.send_error(404)

    def _serve_login_page(self, message: str):
        html = LOGIN_PAGE_HTML.format(message=message)
        body = html.encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def build_ssl_context() -> ssl.SSLContext:
    """
    Build an SSLContext using the self-signed cert and key generated by
    generate_certs.sh.  ssl.PROTOCOL_TLS_SERVER auto-negotiates the best
    TLS version supported by both client and server (TLS 1.2 / 1.3).

    SECURITY CONCEPT: This implements:
      • Confidentiality  — encrypted payload
      • Integrity        — TLS MAC/AEAD prevents tampering
      • Identity         — server certificate authenticates server to client
    """
    if not os.path.exists(CERT_FILE) or not os.path.exists(KEY_FILE):
        print(f"\n  [ERROR] Certificate files not found!")
        print(f"          Expected: {CERT_FILE}")
        print(f"          Expected: {KEY_FILE}")
        print("          Run:  bash generate_certs.sh   (in module_a_traffic/)")
        sys.exit(1)

    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.load_cert_chain(certfile=CERT_FILE, keyfile=KEY_FILE)
    return ctx


def main():
    print("=" * 60)
    print("  MODULE A — SECURE HTTPS SERVER (TC-02 Mitigation)")
    print("=" * 60)
    print(f"  Listening on https://{HOST}:{PORT}")
    print("  🔒 TLS enabled — credentials are ENCRYPTED in transit")
    print("  Run sniffer_agent.py in another terminal (observe TLS handshake only).")
    print("  Browser: accept the self-signed cert warning, then proceed.")
    print("  Press Ctrl+C to stop.\n")

    try:
        ssl_ctx = build_ssl_context()
        socketserver.TCPServer.allow_reuse_address = True
        with socketserver.TCPServer((HOST, PORT), SecureLoginHandler) as httpd:
            # Wrap the raw socket with the SSL context — this is where
            # TLS kicks in: every byte sent/received is now encrypted.
            httpd.socket = ssl_ctx.wrap_socket(httpd.socket, server_side=True)
            httpd.serve_forever()
    except PermissionError:
        print(f"  [ERROR] Permission denied on port {PORT}.")
        sys.exit(1)
    except KeyboardInterrupt:
        print("\n  [INFO] Secure server stopped by user.")


if __name__ == "__main__":
    main()
