#!/usr/bin/env python3
"""
secure_server.py — Module A: HTTPS Server with TLS (Secure Mitigation)
=======================================================================
SECURITY CONCEPT: Confidentiality via TLS/SSL
This server wraps the same login form in TLS using a self-signed certificate
generated by OpenSSL. Credentials are now encrypted end-to-end, making them
unreadable to any passive network observer (tshark/pyshark will show only
the TLS Handshake, not the plaintext payload).

This directly implements the CIA Triad principle of CONFIDENTIALITY via
Cryptographic Transport-Layer Security (TLS 1.2/1.3).

Pre-requisite: Run generate_certs.sh first to create server.crt and server.key
Test Case: TC-02
"""

import http.server
import ssl
import socketserver
import urllib.parse
import os
import sys

# ----- Configuration -------------------------------------------------------
PORT = 8443            # Standard HTTPS alternate port
HOST = "0.0.0.0"
CERT_FILE = os.path.join(os.path.dirname(__file__), "server.crt")
KEY_FILE  = os.path.join(os.path.dirname(__file__), "server.key")

# The same HTML login form — identical UI, but now encrypted in transit
LOGIN_PAGE_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Secure Login (HTTPS Demo)</title>
    <style>
        body {{ font-family: Arial, sans-serif; background: #f0f5f0;
               display: flex; justify-content: center; align-items: center;
               height: 100vh; margin: 0; }}
        .box {{ background: white; padding: 40px; border-radius: 8px;
                box-shadow: 0 4px 12px rgba(0,0,0,0.15); width: 320px; }}
        h2   {{ color: #006600; text-align: center; margin-bottom: 8px; }}
        .info{{ color: #006600; font-size: 12px; text-align: center;
                margin-bottom: 20px; }}
        input{{ width: 100%; padding: 10px; margin: 8px 0; box-sizing: border-box;
                border: 1px solid #ddd; border-radius: 4px; }}
        button{{ width: 100%; padding: 12px; background: #006600; color: white;
                 border: none; border-radius: 4px; cursor: pointer; font-size: 15px; }}
        button:hover {{ background: #004400; }}
    </style>
</head>
<body>
  <div class="box">
    <h2>🔒 Secure HTTPS Login</h2>
    <p class="info">[ TLS Encrypted — Credentials are PROTECTED in transit ]</p>
    <form method="POST" action="/login">
      <input type="text"     name="username" placeholder="Username" required>
      <input type="password" name="password" placeholder="Password" required>
      <button type="submit">Login (TLS Encrypted)</button>
    </form>
    {message}
  </div>
</body>
</html>"""


class SecureLoginHandler(http.server.BaseHTTPRequestHandler):
    """
    Identical handler logic to InsecureLoginHandler, but the underlying
    socket is wrapped in an SSLContext — so all bytes on the wire are
    encrypted. tshark will only see TLS record headers, not the POST body.
    """

    def log_message(self, format, *args):
        print(f"  [HTTPS SERVER] {self.address_string()} → {format % args}")

    def do_GET(self):
        if self.path in ("/", "/login"):
            self._serve_login_page("")
        else:
            self.send_error(404, "Not Found")

    def do_POST(self):
        """
        POST body is the same application/x-www-form-urlencoded data,
        but now it travels inside an encrypted TLS record — invisible to sniffers.
        """
        if self.path == "/login":
            content_length = int(self.headers.get("Content-Length", 0))
            post_body = self.rfile.read(content_length).decode("utf-8")

            params = urllib.parse.parse_qs(post_body)
            username = params.get("username", [""])[0]
            password = params.get("password", [""])[0]

            print("\n" + "=" * 60)
            print("  [✔] ENCRYPTED CREDENTIALS DECRYPTED AT SERVER SIDE")
            print(f"       Username : {username}")
            print(f"       Password : {password}")
            print("  [✔] A wire-sniffer sees ONLY the TLS handshake — NOT this!")
            print("=" * 60 + "\n")

            msg = f'<p style="color:green;text-align:center;">Received securely: <b>{username}</b></p>'
            self._serve_login_page(msg)
        else:
            self.send_error(404)

    def _serve_login_page(self, message: str):
        html = LOGIN_PAGE_HTML.format(message=message)
        body = html.encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def build_ssl_context() -> ssl.SSLContext:
    """
    Build an SSLContext using the self-signed cert and key generated by
    generate_certs.sh.  ssl.PROTOCOL_TLS_SERVER auto-negotiates the best
    TLS version supported by both client and server (TLS 1.2 / 1.3).

    SECURITY CONCEPT: This implements:
      • Confidentiality  — encrypted payload
      • Integrity        — TLS MAC/AEAD prevents tampering
      • Identity         — server certificate authenticates server to client
    """
    if not os.path.exists(CERT_FILE) or not os.path.exists(KEY_FILE):
        print(f"\n  [ERROR] Certificate files not found!")
        print(f"          Expected: {CERT_FILE}")
        print(f"          Expected: {KEY_FILE}")
        print("          Run:  bash generate_certs.sh   (in module_a_traffic/)")
        sys.exit(1)

    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.load_cert_chain(certfile=CERT_FILE, keyfile=KEY_FILE)
    return ctx


def main():
    print("=" * 60)
    print("  MODULE A — SECURE HTTPS SERVER (TC-02 Mitigation)")
    print("=" * 60)
    print(f"  Listening on https://{HOST}:{PORT}")
    print("  🔒 TLS enabled — credentials are ENCRYPTED in transit")
    print("  Run sniffer_agent.py in another terminal (observe TLS handshake only).")
    print("  Browser: accept the self-signed cert warning, then proceed.")
    print("  Press Ctrl+C to stop.\n")

    try:
        ssl_ctx = build_ssl_context()
        socketserver.TCPServer.allow_reuse_address = True
        with socketserver.TCPServer((HOST, PORT), SecureLoginHandler) as httpd:
            # Wrap the raw socket with the SSL context — this is where
            # TLS kicks in: every byte sent/received is now encrypted.
            httpd.socket = ssl_ctx.wrap_socket(httpd.socket, server_side=True)
            httpd.serve_forever()
    except PermissionError:
        print(f"  [ERROR] Permission denied on port {PORT}.")
        sys.exit(1)
    except KeyboardInterrupt:
        print("\n  [INFO] Secure server stopped by user.")


if __name__ == "__main__":
    main()
